export interface Product {
  name: string;
  price: number;
  imageUrl: string;
  categories: string[];
  description: string;
  stock: number;
}

export const products: Product[] = [
  {
    name: "Smartphone Samsung Galaxy A34",
    price: 320,
    imageUrl: "https://media.falabella.com/falabellaPE/119680686_01/public",
    categories: ["Electrónica", "Tecnología Móvil"],
    description: "El Samsung Galaxy A34 ofrece una experiencia móvil excepcional con su pantalla Super AMOLED de 6.6 pulgadas...",
    stock: 0,
  },
  {
    name: "Sofá de 3 plazas gris",
    price: 480,
    imageUrl: "https://yolodecoro.pe/wp-content/uploads/2024/08/SOFAIR3CUE002_3.jpg",
    categories: ["Hogar", "Muebles"],
    description: "Este sofá de 3 plazas combina confort y diseño moderno con su tapizado en tela gris suave al tacto...",
    stock: 5,
  },
  {
    name: "Laptop HP Pavilion 15",
    price: 750,
    imageUrl: "https://www.acomputerservice.com.pe/1506/hp-pavilion-15-eh1070-155-ryzen-7-5700u-18ghz-8gb-512gb.jpg",
    categories: ["Electrónica", "Computación"],
    description: "Laptop con procesador Intel Core i5, 8GB RAM y SSD de 256GB. Pantalla Full HD de 15.6 pulgadas, ideal para trabajo y entretenimiento.",
    stock: 8,
  },
  {
    name: "Smart TV LG 55\" 4K UHD",
    price: 699,
    imageUrl: "https://http2.mlstatic.com/D_NQ_NP_700380-MLU77931382600_082024-O.webp",
    categories: ["Electrónica", "Entretenimiento"],
    description: "Televisor inteligente con resolución 4K, tecnología HDR y webOS. Conexión WiFi, Bluetooth y múltiples puertos HDMI.",
    stock: 10,
  },
  {
    name: "Cafetera Nespresso Essenza Mini",
    price: 99,
    imageUrl: "https://www.multimax.net/cdn/shop/files/Captura_de_Pantalla_2025-04-02_a_la_s_11.41.43_a._m._600x.png?v=1744391612",
    categories: ["Hogar", "Electrodomésticos"],
    description: "Cafetera compacta para preparar espresso perfecto en segundos. Sistema de cápsulas, presión de 19 bares y apagado automático.",
    stock: 25,
  },
  {
    name: "Mesa de centro moderna",
    price: 120,
    imageUrl: "https://oechsle.vteximg.com.br/arquivos/ids/7541961-1000-1000/image-a4894028cc5143c49b1fd2a05c7f424e.jpg?v=637822552389230000",
    categories: ["Hogar", "Muebles"],
    description: "Mesa de centro rectangular en acabado de madera y metal. Diseño minimalista con espacio de almacenamiento inferior.",
    stock: 7,
  },
  {
    name: "Set de sartenes antiadherentes",
    price: 85,
    imageUrl: "https://www.cocinaconbra.com/cdn/shop/products/Set3-sartenes-aluminio-forjado-antiadherente-2_900x.jpg?v=1627902853",
    categories: ["Hogar", "Cocina"],
    description: "Set de 3 sartenes con recubrimiento antiadherente libre de PFOA. Mangos ergonómicos resistentes al calor.",
    stock: 15,
  },
  {
    name: "Audífonos Sony WH-1000XM4",
    price: 349,
    imageUrl: "https://i.blogs.es/7af9e0/sony-wh-1000xm4-analisis/1366_2000.jpg",
    categories: ["Electrónica", "Audio"],
    description: "Audífonos inalámbricos con cancelación de ruido líder en la industria. Hasta 30 horas de batería y asistente de voz integrado.",
    stock: 6,
  },
  {
    name: "Bicicleta montañera Trek Marlin 5",
    price: 599,
    imageUrl: "https://uploads.tiendada.com/public/file-storage/im/product/615a98e4-2206-4dee-aaea-4643b22fc332.jpg",
    categories: ["Deportes", "Outdoor"],
    description: "Bicicleta para montaña con cuadro de aluminio, 21 velocidades y frenos de disco mecánicos. Ideal para senderos.",
    stock: 3,
  },
  {
    name: "Reloj inteligente Xiaomi Mi Band 7",
    price: 59,
    imageUrl: "https://http2.mlstatic.com/D_NQ_NP_984324-MLA53251960164_012023-O.webp",
    categories: ["Electrónica", "Wearables"],
    description: "Pulsera inteligente con pantalla AMOLED de 1.62\", monitoreo de ritmo cardíaco, SpO2 y más de 100 modos deportivos.",
    stock: 30,
  },
  {
    name: "Juego de mesa Catan",
    price: 45,
    imageUrl: "https://media.falabella.com/falabellaPE/17672696_1/w=1500,h=1500,fit=pad",
    categories: ["Entretenimiento", "Juegos"],
    description: "El clásico juego de estrategia donde construyes asentamientos, recolectas recursos y compites por la supremacía en la isla.",
    stock: 18,
  },
  {
    name: "Cámara GoPro Hero 10",
    price: 399,
    imageUrl: "https://i.blogs.es/b44142/gopro-hero-10-black-2-/1366_2000.jpg",
    categories: ["Electrónica", "Fotografía"],
    description: "Cámara deportiva 4K con estabilización HyperSmooth 4.0, resistente al agua hasta 10m sin carcasa y pantalla táctil.",
    stock: 9,
  },
  {
    name: "Maleta de viaje 20\"",
    price: 89,
    imageUrl: "https://pe.kennethcolelatino.com/cdn/shop/files/KC02-20_GUNMETAL_2.jpg?v=1740581854",
    categories: ["Viajes", "Outdoor"],
    description: "Maleta cabina con ruedas 360°, sistema de bloqueo TSA y compartimentos organizados. Material resistente y ligero.",
    stock: 14,
  },
  {
    name: "Robot aspirador Xiaomi",
    price: 299,
    imageUrl: "https://example.com/robot-aspirador.jpg",
    categories: ["Hogar", "Electrodomésticos"],
    description: "Aspiradora robot con navegación láser, mapeo inteligente y control por app. Limpieza programable y compatible con asistentes de voz.",
    stock: 5,
  },
  {
    name: "Parlante Bluetooth JBL Flip 5",
    price: 119,
    imageUrl: "https://example.com/jbl-flip.jpg",
    categories: ["Electrónica", "Audio"],
    description: "Parlante portátil con sonido potente, resistencia al agua IPX7 y hasta 12 horas de reproducción. Disponible en varios colores.",
    stock: 22,
  },
  {
    name: "Mochila para laptop 15.6\"",
    price: 49,
    imageUrl: "https://example.com/mochila.jpg",
    categories: ["Computación", "Oficina"],
    description: "Mochila con compartimento acolchado para laptop, múltiples bolsillos organizadores y diseño ergonómico para mayor comodidad.",
    stock: 30,
  },
  {
    name: "Set de maquillaje profesional",
    price: 65,
    imageUrl: "https://example.com/maquillaje.jpg",
    categories: ["Belleza", "Cuidado personal"],
    description: "Kit completo con 12 sombras, 2 rubores, 2 labiales y brochas de alta calidad. Ideal para looks diarios y de noche.",
    stock: 17,
  },
  {
    name: "Silla gamer ergonómica",
    price: 199,
    imageUrl: "https://example.com/silla-gamer.jpg",
    categories: ["Muebles", "Computación"],
    description: "Silla con soporte lumbar, reposacabezas ajustable y materiales transpirables. Base metálica resistente hasta 120kg.",
    stock: 8,
  },
  {
    name: "Teclado mecánico RGB",
    price: 79,
    imageUrl: "https://example.com/teclado.jpg",
    categories: ["Computación", "Electrónica"],
    description: "Teclado mecánico con switches Blue, retroiluminación RGB personalizable y diseño resistente a salpicaduras.",
    stock: 25,
  },
  {
    name: "Monitor curvo 27\" Samsung",
    price: 249,
    imageUrl: "https://example.com/monitor-curvo.jpg",
    categories: ["Electrónica", "Computación"],
    description: "Monitor Full HD con curvatura 1800R, tiempo de respuesta 4ms y tecnología Eye Care para mayor comodidad visual.",
    stock: 12,
  },
  {
    name: "Cortadora de césped inalámbrica",
    price: 189,
    imageUrl: "https://example.com/cortadora.jpg",
    categories: ["Hogar", "Jardín"],
    description: "Cortadora con motor de 40V y batería de litio. Ancho de corte de 33cm y altura ajustable en 5 posiciones.",
    stock: 6,
  },
  {
    name: "Horno tostador digital",
    price: 55,
    imageUrl: "https://example.com/horno-tostador.jpg",
    categories: ["Hogar", "Electrodomésticos"],
    description: "Horno tostador con capacidad de 15L, temporizador digital y función de convección para cocción uniforme.",
    stock: 20,
  },
  {
    name: "Dron DJI Mini 2",
    price: 449,
    imageUrl: "https://example.com/dji-drone.jpg",
    categories: ["Electrónica", "Fotografía"],
    description: "Dron compacto con cámara 4K, transmisión de video HD de 10km y batería de 31 minutos. Peso inferior a 249g.",
    stock: 4,
  },
  {
    name: "Impresora multifuncional HP",
    price: 129,
    imageUrl: "https://example.com/impresora.jpg",
    categories: ["Oficina", "Electrónica"],
    description: "Impresora todo-en-uno con WiFi, escáner y copiadora. Compatible con HP Instant Ink y aplicaciones móviles.",
    stock: 15,
  },
  {
    name: "Cojín lumbar de memoria",
    price: 35,
    imageUrl: "https://example.com/cojin-lumbar.jpg",
    categories: ["Hogar", "Oficina"],
    description: "Cojín ergonómico con memoria viscoelástica que se adapta a la forma de tu espalda. Funda removible y transpirable.",
    stock: 40,
  },
  {
    name: "Licuadora profesional Oster",
    price: 89,
    imageUrl: "https://example.com/licuadora.jpg",
    categories: ["Hogar", "Electrodomésticos"],
    description: "Licuadora de 1200W con jarra de vidrio de 1.5L, 10 velocidades y función pulso. Cuchillas de acero inoxidable.",
    stock: 12,
  },
  {
    name: "Tabla de picar bambú",
    price: 22,
    imageUrl: "https://example.com/tabla-picar.jpg",
    categories: ["Hogar", "Cocina"],
    description: "Tabla de picar ecológica de bambú con superficie antideslizante. Resistente a cortes y fácil de limpiar.",
    stock: 50,
  },
  {
    name: "Altavoz inteligente Amazon Echo",
    price: 79,
    imageUrl: "https://example.com/echo-dot.jpg",
    categories: ["Electrónica", "Hogar"],
    description: "Altavoz con Alexa, control por voz para tu hogar inteligente. Sonido nítido y diseño compacto.",
    stock: 25,
  },
  {
    name: "Cepillo dental eléctrico Oral-B",
    price: 49,
    imageUrl: "https://example.com/oralb.jpg",
    categories: ["Belleza", "Cuidado personal"],
    description: "Cepillo eléctrico con tecnología oscilante-rotante, temporizador y 1 cabezal de repuesto incluido.",
    stock: 30,
  },
  {
    name: "Termo de acero inoxidable 500ml",
    price: 29,
    imageUrl: "https://example.com/termo.jpg",
    categories: ["Hogar", "Outdoor"],
    description: "Termo que mantiene líquidos fríos por 24h y calientes por 12h. Diseño resistente y libre de BPA.",
    stock: 45,
  },
  {
    name: "Set de herramientas 85 piezas",
    price: 65,
    imageUrl: "https://example.com/herramientas.jpg",
    categories: ["Hogar", "Herramientas"],
    description: "Juego completo de herramientas manuales para reparaciones domésticas. Incluye destornilladores, llaves, alicates y más.",
    stock: 18,
  },
  {
    name: "Mesa plegable para camping",
    price: 42,
    imageUrl: "https://example.com/mesa-camping.jpg",
    categories: ["Outdoor", "Hogar"],
    description: "Mesa ligera y plegable de aluminio. Resistente al agua y fácil de transportar. Dimensiones: 60x60cm.",
    stock: 10,
  }
];